// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Usando_EntityFramework.Data;

#nullable disable

namespace UsandoEntityFramework.Migrations
{
    [DbContext(typeof(ProdutosContext))]
    partial class ProdutosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Usando_EntityFramework.Models.Produtos", b =>
                {
                    b.Property<int>("Codigo_do_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_do_produto"));

                    b.Property<string>("Embalagem_do_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_do_produto")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Preco_do_produto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sabor_do_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tamanho_do_produto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo_do_produto");

                    b.ToTable("Produto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
